# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b942306c8182cc1aea9418904e1e6bb252fbe4d8b5e80087270aab3c90e186b5486cd6fb96aaf8182aa962c24479da8ab89670e6f5d3b55779bade4080738b6

test:
  secret_key_base: 7462f9be5643826bd453388b7cf9657bcd8e37400a84de1bd1855d96562b2ac5f1e75c637618c18d592320dc0ac926d323e1cecda9945cf93197efb7bcd20a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
